### ISSUE TITLE
Add a file using api

### ISSUE THREAD

**Issue by aniket-kumar** [ipfs/faq#131] opened 2016-06-08 07:46 UTC
I want to create a webpage in which user will upload a file and that file will be uploaded on ipfs and i will get the hash of file internally. I think i can do this using the apis of ipfs but i didn't get any particular documentation of ipfs apis. Tell me, How can i solve this purpose?

**Comment by harshetha** [comment] 2016-06-08 15:26
I am working on a very similar project where I need a webapp to upload a file onto ipfs and retrieve the object hash. I have a general outline of how it works if you're interested. Any progress/luck?

**Comment by aniket-kumar** [comment] 2016-06-09 07:29
@Harshetha  I am not able to see your comment. I think your response can help a lot to solve this issue. Thanks in advance

**Comment by harshetha** [comment] 2016-06-09 13:48
I am working on a web scenario where I have to upload a file into ipfs and
then retrieve the document hash. I am working off of this code I have
linked but it is not fully functional, just a general idea of how to call
functions from the ipfs api using Node.js.
https://github.com/ipfs/examples/issues/17
Let me know if you find something further and I will do the same

**Comment by aniket-kumar** [comment] 2016-06-09 14:14
I have tried multiple approaches found from anywhere but none of them is working to upload a file. Yeah, i come to learn how to upload text only. I don't know if any api of ipfs is made for this purpose.

**Comment by harshetha** [comment] 2016-06-09 19:20
Can I see how you uploaded text? Maybe I can add some commands and combine
my knowledge to figure out how to upload a file.

**Comment by aniket-kumar** [comment] 2016-06-10 06:14
I just followed this : 
https://www.npmjs.com/package/ipfs-js

let me know about any progress... :)

**Comment by harshetha** [comment] 2016-06-10 13:55
I have tried this before but it did not work for me, can I see your code
and file structure?

Thanks
Harshetha

**Comment by harshetha** [comment] 2016-06-10 14:03
I also think I know how to integrate the file upload with ipfs but having a
few issues

**Comment by aniket-kumar** [comment] 2016-06-10 14:11
It was also not working on my system but when i uploaded it to ipfs and executed it from ipfs then it worked for me. Try that. Follow all the steps given in that link till 4th one.

**Comment by aniket-kumar** [comment] 2016-06-13 11:33
@harshetha any progress?

**Comment by harshetha** [comment] 2016-06-13 14:08
No, the issue is that the files.add function is not yet implemented in the
index.js or the load-commands.js (these files are called in the ipfs api),
we either need to write our own function or find someone's fork that
already has it.

**Comment by aniket-kumar** [comment] 2016-06-13 14:09
yeah, you are right. I was also thinking same.

**Comment by harshetha** [comment] 2016-06-13 15:06
I am also trying out this
https://www.npmjs.com/package/ipfs-client#add---store-the-content-of-a-stream

**Comment by aniket-kumar** [comment] 2016-06-14 11:30
ok, let me know about any progress...go ahead

**Comment by RichardLitt** [comment] 2016-06-14 11:33
@diasdavid Can you answer this?

**Comment by daviddias** [comment] 2016-06-14 21:59
You can upload a file to IPFS using the `js-ipfs-api`(HTTP Client Library, works with Go or JS IPFS nodes) or `js-ipfs` (Full node in JS) using the interface defined here https://github.com/ipfs/interface-ipfs-core#files

Try first using https://github.com/ipfs/js-ipfs-api and the go-ipfs daemon and let me know of your results. Note that you will have to set the CORS headers this way https://github.com/ipfs/js-ipfs-api#cors

**Comment by aniket-kumar** [comment] 2016-06-15 05:36
@diasdavid i tried this js-ipfs-api. It is working fine for ipfs.id but when i tried to use **ipfs.add("string").then(callback)** , it showed the error : _Uncaught TypeError: ipfs.add is not a function_

**Comment by daviddias** [comment] 2016-06-15 06:04
@aniket-kumar, try with `ipfs.files.add`

**Comment by aniket-kumar** [comment] 2016-06-15 06:16
@diasdavid now new error : <code>Uncaught TypeError: cb is not a function</code> in add.js
I am trying to add  the string as _ipfs.files.add("hey")_ . I also tried it with hex and binary format of string. It is giving the same error.

**Comment by aniket-kumar** [comment] 2016-06-23 05:22
@harshetha @RichardLitt @diasdavid  any new findings?

**Comment by ttaveira** [comment] 2016-07-05 15:27
I'm trying to do the same thing. If I understand correctly, `ipfs.files.add` requires a `Buffer`or `Readable Stream` (Node.js types). Are we able to use the [js-ipfs-api](https://github.com/ipfs/js-ipfs-api/blob/master/API.md) without Node?

Also, is there any difference between `ipfs.files.add` and `ipfs.add`?

**Comment by neuronsupport** [comment] 2016-11-21 15:22
ipfs-js is node.js only I guess. If we could not write/move/copy/delete files from web browser in a way, how would ipfs be useful to anyone other than showing static web pages.

**Comment by victorb** [comment] 2016-11-22 12:01
@aniket-kumar

You have two different ways of using the `ipfs.files.add` method. Either you define a callback like this:

```
ipfs.files.add([new Buffer('hello world')], (err, res) => {
// do something with res
})
```

Or use it with promises:


```
ipfs.files.add([new Buffer('hello world')]).then((res) => {
// do something with res
}).catch((err) => { /* handle err */ })
```

It's mentioned in the readme over here: https://github.com/ipfs/js-ipfs-api#callbacks-and-promises

@ttaveira 

> Are we able to use the js-ipfs-api without Node?

Yes, it works in the browser as well. You have some examples here: https://github.com/ipfs/js-ipfs-api/tree/master/examples

> Also, is there any difference between ipfs.files.add and ipfs.add?

No, it's merely there to fulfill the interface we defined in https://github.com/ipfs/interface-ipfs-core/ while remaining backwards compatibility. 

@norzak No, js-ipfs works in the browser as well. There are examples in the repository itself (here: https://github.com/ipfs/js-ipfs/tree/master/examples) and I've also made an example for passing around data you can check out here: https://github.com/VictorBjelkholm/js-ipfs-passing-data

I'm gonna close this issue, and refer to future readers to open up issues in the appropriate repository if you're having any troubles with either js-ipfs or js-ipfs-api

**Comment by Kubuxu** [comment] 2016-11-22 13:31
We are leaving issues open in FAQ repo so they are more easily visible.

**Comment by flyingzumwalt** [comment] 2017-05-23 00:09
This issue was moved to https://discuss.ipfs.io/t/add-a-file-using-api/278

**Closed as completed by flyingzumwalt** 2017-05-23 00:09 UTC
Labels: answered

**Comment by vurumadla** [comment] 2017-09-06 10:15
hi can anyone give a solution to this..

GET /frontend/css/bootstrap.min.css.map 404 2.993 ms - -
req :Bg-Amendment-Chaincode.docx
ReferenceError: document is not defined
    at Object.handle (D:\TF_23_8\TF_LATEST\appOriginal.js:274:15)
    at next_layer (D:\TF_23_8\TF_LATEST\node_modules\express\lib\router\route.js:103:13)
    at Route.dispatch (D:\TF_23_8\TF_LATEST\node_modules\express\lib\router\route.js:107:5)
    at D:\TF_23_8\TF_LATEST\node_modules\express\lib\router\index.js:195:24
    at param (D:\TF_23_8\TF_LATEST\node_modules\express\lib\router\index.js:268:14)
    at param (D:\TF_23_8\TF_LATEST\node_modules\express\lib\router\index.js:280:16)
    at Function.proto.process_params (D:\TF_23_8\TF_LATEST\node_modules\express\lib\router\index.js:296:3)
    at next (D:\TF_23_8\TF_LATEST\node_modules\express\lib\router\index.js:189:19)
    at Layer.staticMiddleware [as handle] (D:\TF_23_8\TF_LATEST\node_modules\express\node_modules\serve-static\index.js:55:61)
    at trim_prefix (D:\TF_23_8\TF_LATEST\node_modules\express\lib\router\index.js:226:17)
POST /file-upload:Bg-Amendment-Chaincode.docx 500 119.852 ms - 937
POST /file-upload:Bg-Amendment-Chaincode.docx 500 121.013 ms - 937
[ibc-js] GetAllLC  - failure: 408 Request timed out
