### ISSUE TITLE
webui locale issue

### ISSUE THREAD

**Issue by leochan007** [ipfs/faq#113] opened 2016-04-27 08:18 UTC
after i exec "ipfs daemon"
i got this error output

ERROR core/serve: Path Resolve error: no link named "webui-zh.json" under QmcnV8mXz9B4kuNEUymZ2mhqDLy2e76iMMk8SnmPDnxp6H gateway_handler.go:510

**Comment by RichardLitt** [comment] 2016-04-27 11:41
Looks like a go-ipfs bug. @whyrusleeping?

**Comment by RichardLitt** [comment] 2016-04-27 11:42
Closed as duplicate of https://github.com/ipfs/go-ipfs/issues/2609.

**Closed as completed by RichardLitt** 2016-04-27 11:42 UTC
